networks:
  proxy:
    external: true
  torrents:
    driver: bridge

services:
  rtorrent:
    build: .
    container_name: rtorrent
    networks:
      - torrents
    restart: unless-stopped
    ports:
      - "50000:50000/tcp"
      # - "50000:50000/udp"
      - "5000:5000"
    volumes:
      - /mnt/torrents/config:/config:ro
      - ./rtorrent/session:/session
      - /mnt/torrents/watch:/watch
      - /mnt/torrents/files:/files
      - /mnt/torrents/log:/log

  rutorrent:
    image: lscr.io/linuxserver/rutorrent:latest
    container_name: rutorrent
    depends_on:
      - rtorrent
    networks:
      - torrents
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /mnt/torrents/config:/config
      - /mnt/torrents/files:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rutorrent.rule=Host(`torrent.${DOMAIN}`)"
      - "traefik.http.routers.rutorrent.entrypoints=websecure"
      - "traefik.http.routers.rutorrent.tls.certresolver=letsencrypt"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

