services:
  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    restart: unless-stopped

    ports:
      - "50000:50000/tcp"
      - "50000:50000/udp"

    networks:
      - proxy

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      RT_DHT_PORT: "0"
      RT_INC_PORT: "50000"
      XMLRPC_PORT: "5000"
      RUTORRENT_PORT: "80"
      MEMORY_LIMIT: "4096M"
      RU_DO_DIAGNOSTIC: "false"
      RU_REMOVE_CORE_PLUGINS: "true"
      WAN_IP_CMD: "false"

    volumes:
      - /mnt/torrents/config:/config:ro
      - /mnt/torrents/config/rtorrent/.rtorrent.rc:/data/rtorrent/.rtorrent.rc
      - /mnt/torrents/session:/data/rtorrent/rtorrent_sess
      - /mnt/torrents/watch:/watch
      - /mnt/torrents/files:/files
      - /mnt/torrents/log:/log

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rutorrent.rule=Host(`torrents.${DOMAIN}`)"
      - "traefik.http.routers.rutorrent.entrypoints=websecure"
      - "traefik.http.routers.rutorrent.tls.certresolver=letsencrypt"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
