services:
  rtorrent:
    image: crazymax/rtorrent-rutorrent:4.3.1-0.9.8_3-0.13.8_2
    container_name: rtorrent
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      RT_DHT_PORT: "0"
      RT_INC_PORT: "50000"
      XMLRPC_PORT: "5000"
      RUTORRENT_PORT: "80"
      MEMORY_LIMIT: "4096M"
      RU_DO_DIAGNOSTIC: "false"
      RU_REMOVE_CORE_PLUGINS: "true"
      WAN_IP_CMD: "false"
    ports:
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "192.168.50.50:8101:80"
    volumes:
      - /mnt/torrents/config:/config:ro
      - /mnt/torrents/config/rtorrent/:/data/rtorrent/
      - /mnt/torrents/session:/session
      - /mnt/torrents/watch:/watch
      - /mnt/torrents/files:/files
      - /mnt/torrents/log:/log
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rutorrent.rule=Host(`torrents.${DOMAIN}`)"
      - "traefik.http.routers.rutorrent.entrypoints=websecure"
      - "traefik.http.routers.rutorrent.tls.certresolver=letsencrypt"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=80"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks: [ proxy ]
    environment:
      PUID: 3001
      PGID: 3001
      TZ: ${TZ}
    volumes:
      - ./jellyfin:/config
      - /mnt/torrents/files:/media
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "109"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.jellyfin.rule=Host(`media.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.services.jellyfin.loadBalancer.passHostHeader=true"
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "192.168.50.50:8096:8096"

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    networks: [ proxy ]
    volumes:
      - /mnt/torrents:/srv:rw
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
      - ./filebrowser/filebrowser.db:/database/filebrowser.db
    environment:
      TZ: ${TZ}
      FB_BASEURL: /files
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.filebrowser.rule=Host(`files.${DOMAIN}`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "192.168.50.50:8102:80"

  kavita:
    image: ghcr.io/kareadita/kavita:latest
    container_name: kavita
    restart: unless-stopped
    networks: [ proxy ]
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - /mnt/library/books:/books
      - ./kavita/config:/kavita/config
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.kavita.rule=Host(`books.${DOMAIN}`)"
      - "traefik.http.routers.kavita.entrypoints=websecure"
      - "traefik.http.routers.kavita.tls.certresolver=letsencrypt"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "192.168.50.50:8103:5000"

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    networks: [ proxy ]
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - /mnt/archive/library/audio:/audiobooks
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audio.${DOMAIN}`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=websecure"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=letsencrypt"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "192.168.50.50:8104:80"

networks:
  proxy:
    external: true
